### ISSUE TITLE
Blurry text/icons while marquee is scrolling

### ISSUE THREAD

**Issue by dhunninghake** [mattiacoll/vanilla-marquee#1]
Hey! Well done on this package - fits my use case perfectly.

Just had one little bug come up that might help others - icons and text show up blurry when the marquee starts scrolling.

I was able to fix it with a line of CSS, might be useful to add a patch release eventually:

```css
.js-marquee {
  backface-visibility: hidden;
}
```
